//
// This file was auto-generated by the generateVectorExtensions gradle task!
//

package com.github.mnemotechnician.mkui.extensions

import arc.graphics.Color
import com.github.mnemotechnician.mkui.extensions.*

/** Creates a new Color that is the result of the operation "this plus other". */
inline operator fun Color.plus(other: Color): Color = Color(this).add(other)

/** Modifies this Color so that its value is the result of the operation "this plus other". */
inline operator fun Color.plusAssign(other: Color) {
	add(other)
}

/** Creates a new Color that is the result of the operation "this minus other". */
inline operator fun Color.minus(other: Color): Color = Color(this).sub(other)

/** Modifies this Color so that its value is the result of the operation "this minus other". */
inline operator fun Color.minusAssign(other: Color) {
	sub(other)
}

/** Creates a new Color that is the result of the operation "this times other". */
inline operator fun Color.times(other: Color): Color = Color(this).mul(other)

/** Modifies this Color so that its value is the result of the operation "this times other". */
inline operator fun Color.timesAssign(other: Color) {
	mul(other)
}

/** Creates a new Color that is the result of the operation "this times other". */
inline operator fun Color.times(other: Float): Color = Color(this).mul(other)

/** Modifies this Color so that its value is the result of the operation "this times other". */
inline operator fun Color.timesAssign(other: Float) {
	mul(other)
}