//
// This file was auto-generated by the generateVectorExtensions gradle task!
//

package com.github.mnemotechnician.mkui.extensions

import arc.math.geom.Vec3
import com.github.mnemotechnician.mkui.extensions.*

/** Creates a new Vec3 that is the result of the operation "this plus other". */
inline operator fun Vec3.plus(other: Vec3): Vec3 = Vec3(this).add(other)

/** Modifies this Vec3 so that its value is the result of the operation "this plus other". */
inline operator fun Vec3.plusAssign(other: Vec3) {
	add(other)
}

/** Creates a new Vec3 that is the result of the operation "this minus other". */
inline operator fun Vec3.minus(other: Vec3): Vec3 = Vec3(this).sub(other)

/** Modifies this Vec3 so that its value is the result of the operation "this minus other". */
inline operator fun Vec3.minusAssign(other: Vec3) {
	sub(other)
}

/** Creates a new Vec3 that is the result of the operation "this times other". */
inline operator fun Vec3.times(other: Vec3): Vec3 = Vec3(this).mul(other)

/** Modifies this Vec3 so that its value is the result of the operation "this times other". */
inline operator fun Vec3.timesAssign(other: Vec3) {
	mul(other)
}

/** Creates a new Vec3 that is the result of the operation "this div other". */
inline operator fun Vec3.div(other: Vec3): Vec3 = Vec3(this).div(other)

/** Modifies this Vec3 so that its value is the result of the operation "this div other". */
inline operator fun Vec3.divAssign(other: Vec3) {
	div(other)
}

/** Creates a new Vec3 that is the result of the operation "this times other". */
inline operator fun Vec3.times(other: Float): Vec3 = Vec3(this).mul(other)

/** Modifies this Vec3 so that its value is the result of the operation "this times other". */
inline operator fun Vec3.timesAssign(other: Float) {
	mul(other)
}