name: Deployment
on:
  workflow_dispatch:
    inputs:
      description:
        description: 'release description'
        required: true
        default: '— no description providen'

jobs:
  buildAndUpload:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: compile
        id: compile
        env:
          version: ${{ github.run_number }}
        run: |
          sed -i "s/version = 1\.0/version = $version/g" lib/build.gradle.kts
          chmod +x gradlew
          ./gradlew test jar
          
          echo '::set-output name=description::$( echo '${{ github.event.inputs.description }}' | sed "s/\\\\n/%0A/g" )'
      
      - name: create release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: lib/build/libs/MKUI.jar
          tag: ${{ github.run_number }}
          body: ${{ steps.compile.outputs.description }}
        
      - name: generate kotlin doc
        run: ./gradlew dokkaHtml
        
      - name: upload kotlin doc
        run: |
          rm -rf docs/*
          mkdir -p docs
          mv -f lib/build/dokka/html/* docs/
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          git add -A
          git commit -am "[auto] upload kotlin docs" || true
          git push || true
