name: Deployment
on: workflow_dispatch

jobs:
  buildAndUpload:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: compile
        run: |
          chmod +x gradlew
          ./gradlew test jar
      
      - name: create release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: lib/build/libs/MKUI.jar
          tag: ${{ github.run_number }}
        
      - name: generate kotlin doc
        run: ./gradlew dokkaHtml
        
      - name: upload kotlin doc
        run: |
          rm -rf docs/*
          mkdir -p docs
          mv -f lib/build/dokka/html/* docs/
          git config --global user.name 'Github Actions'
          git config --global user.email 'ci_activity@noreply.github.com'
          git add -A
          git commit -am "[auto] upload kotlin docs"
          git push